### PR TITLE
UI ux

### PR DESCRIPTION
**Pull request by HOOK-Hawkins**
Review TTTK-10

### CODE REVIEW

**Review by Petzys — CHANGES_REQUESTED** [review]
You should add unit tests for the Code. In general, all code should be unit tested.

**Comment by Petzys** [comment]
You should also add comments to classes and functions as this is required by the lecturerer.

**Comment by JM-Lemmi** [comment]
@Tayhm please fix your commit email! >:(

`git config --global user.email s211273@student.dhbw-mannheim.de`

**Comment by JM-Lemmi** [comment]
togeter with #2

**Pull request closed without merging**
